package com.kampusagi.android.core.designsystem.icon

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource
import com.kampusagi.android.R

/**
 * Material Symbols Rounded (fonts.google.com/icons), shipped as vector drawables
 * in res/drawable/ms_*.xml. Every icon in the app comes from here.
 */
object AppIcons {
    val CloudOff: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_cloud_off)
    val ArrowBack: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_arrow_back)
    val ChatBubble: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_chat_bubble)
    val Send: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_send)
    val MarkEmailRead: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_mark_email_read)
    val Lightbulb: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_lightbulb)
    val Inbox: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_inbox)
    val Forum: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_forum)
    val Delete: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_delete)
    val Visibility: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_visibility)
    val VisibilityOff: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_visibility_off)
    val UploadFile: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_upload_file)
    val Tune: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_tune)
    val PersonSearch: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_person_search)
    val Person: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_person)
    val Notifications: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_notifications)
    val MoreVert: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_more_vert)
    val HourglassTop: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_hourglass_top)
    val Favorite: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_favorite)
    val KeyboardArrowDown: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_keyboard_arrow_down)
    val Error: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_error)
    val Edit: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_edit)
    val Close: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_close)
    val CheckCircle: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_check_circle)
    val Block: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_block)
    val Stars: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_stars)
    val Add: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_add)
    val Home: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_home)
    val Group: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_group)
    val Groups: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_groups)
    val Handshake: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_handshake)
    val PhotoCamera: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_photo_camera)
    val AddAPhoto: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_add_a_photo)
    val Settings: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_settings)
    val WorkspacePremium: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_workspace_premium)
    val AdminPanelSettings: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_admin_panel_settings)
    val Logout: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_logout)
    val DarkMode: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_dark_mode)
    val LightMode: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_light_mode)
    val Contrast: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_contrast)
    val Help: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_help)
    val MenuBook: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_menu_book)
    val Event: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_event)
    val Campaign: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_campaign)
    val Storefront: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_storefront)
    val Apartment: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_apartment)
    val Search: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_search)
    val Work: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_work)
    val SportsSoccer: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_sports_soccer)
    val Check: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_check)
    val School: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_school)
    val Verified: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_verified)
    val GridView: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_grid_view)
    val Chat: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_chat)
    val Lock: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_lock)
    val Mail: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_mail)
    val FavoriteFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_favorite_fill)
    val HomeFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_home_fill)
    val LightbulbFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_lightbulb_fill)
    val ChatBubbleFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_chat_bubble_fill)
    val NotificationsFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_notifications_fill)
    val PersonFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_person_fill)
    val HandshakeFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_handshake_fill)
    val ForumFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_forum_fill)
    val Bookmark: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_bookmark)
    val BookmarkFilled: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_bookmark_fill)
    val LocationOn: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_location_on)
    val BarChart: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_bar_chart)
    val Sell: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_sell)
    val CalendarMonth: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_calendar_month)
    val Schedule: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_schedule)
    val AddPhotoAlternate: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_add_photo_alternate)
    val ChevronRight: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_chevron_right)
    val EventAvailable: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_event_available)
    val HowToVote: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_how_to_vote)
    val Remove: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_remove)
    val Info: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_info)
    val PushPin: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_keep)
    val Upload: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_upload)
    val Description: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_description)
    val PersonAdd: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_person_add)
    val PersonRemove: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_person_remove)
    val ShieldPerson: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_shield_person)
    val MilitaryTech: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_military_tech)
    val VolunteerActivism: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_volunteer_activism)
    val LocalFireDepartment: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_local_fire_department)
    val PictureAsPdf: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_picture_as_pdf)
    val ExitToApp: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ms_exit_to_app)
}
