#!/usr/bin/env python3
"""Generates the first published version of every legal text from docs/legal/*.md.

Usage: python3 scripts/generate-legal-migration.py > supabase/migrations/<timestamp>_legal_documents_v1.sql

Only for the initial version. Later versions are published from the admin panel
(KVKK ve Uyum -> Hukuki metinler), which keeps every old version as evidence.
The file name (without .md) is the doc_type; the first "# " line is the title.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "legal"


def main() -> None:
    out = [
        "-- Generated by scripts/generate-legal-migration.py from docs/legal/*.md. Do not edit by hand.",
        "-- Version 1 of every legal text (drafts awaiting legal review; placeholders in [brackets]).",
        "",
    ]
    for path in sorted(DOCS.glob("*.md")):
        doc_type = path.stem
        content = path.read_text(encoding="utf-8").strip() + "\n"
        title = next((line[2:].strip() for line in content.splitlines() if line.startswith("# ")), None)
        if not title:
            sys.exit(f"{path}: missing '# Title' line")
        tag = "$legal$"
        if tag in content:
            sys.exit(f"{path}: contains {tag}")
        out.append(
            "insert into public.legal_documents (doc_type, version, title, content) values "
            f"('{doc_type}', 1, '{title.replace(chr(39), chr(39) * 2)}', {tag}{content}{tag});"
        )
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
