#!/usr/bin/env python3
"""Generates the universities data migration from supabase/data/province-universities.json.

The JSON (provided by the product owner, grouped by province) is the source of
truth. Only the fields the app needs are loaded: name, city and the website
domain (used later to match student email domains). Contact details and
rector names are not copied into the database.

Usage: scripts/generate-universities-migration.py <output.sql>
"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "supabase" / "data" / "province-universities.json"

DOMAIN = re.compile(r"^[a-z0-9.-]+\.[a-z]{2,}$")
LOWER = str.maketrans({"I": "ı", "İ": "i"})


def turkish_title(word: str) -> str:
    lowered = word.translate(LOWER).lower()
    first = lowered[0]
    first = {"i": "İ", "ı": "I"}.get(first, first.upper())
    return first + lowered[1:]


def city_name(province: str) -> str:
    return " ".join(turkish_title(part) for part in province.strip().split())


def website_domain(raw: str):
    value = (raw or "").strip()
    if value in ("", "-"):
        return None
    # Some entries list two addresses ("a.edu.tr / b.edu.tr"): the first is the official one.
    value = value.split()[0]
    # "http:www.x.edu.tr" -> "http://www.x.edu.tr"
    value = re.sub(r"^(https?):(?!//)", r"\1://", value)
    if "://" not in value:
        value = "http://" + value
    host = (urlparse(value).hostname or "").lower()
    if host.startswith("www."):
        host = host[4:]
    if not DOMAIN.match(host):
        raise SystemExit(f"cannot derive a domain from website {raw!r}")
    return host


def sql_text(value):
    return "null" if value is None else "'" + value.replace("'", "''") + "'"


def main(output: str) -> None:
    provinces = json.loads(SOURCE.read_text(encoding="utf-8"))
    rows = []
    for province in provinces:
        city = city_name(province["province"])
        for university in province["universities"]:
            rows.append((university["name"].strip(), city, website_domain(university.get("website"))))
    names = [name for name, _, _ in rows]
    if len(names) != len(set(names)):
        raise SystemExit("duplicate university names in source")
    rows.sort(key=lambda row: row[0])

    values = ",\n".join(f"    ({sql_text(n)}, {sql_text(c)}, {sql_text(d)})" for n, c, d in rows)
    sql = f"""-- Universities from supabase/data/province-universities.json ({len(rows)} institutions, {len(provinces)} provinces).
-- Generated by scripts/generate-universities-migration.py; do not edit by hand.
-- Re-running is safe: existing rows are updated by name, nothing is deleted.

alter table public.universities
    add column if not exists website_domain text
        check (website_domain is null or website_domain ~ '^[a-z0-9.-]+\\.[a-z]{{2,}}$');

insert into public.universities (name, city, website_domain) values
{values}
on conflict (name) do update
    set city = excluded.city,
        website_domain = excluded.website_domain;
"""
    Path(output).write_text(sql, encoding="utf-8")
    print(f"wrote {len(rows)} universities to {output}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
