-- Chat: one-to-one conversations between approved students.
--
-- Receipts come from real data, never from the client's imagination:
--   sent      -> the message row exists on the server,
--   read      -> the other member's last_read_at is at or after the message.
-- New messages reach the other device through Supabase Realtime (postgres
-- changes on public.messages, filtered by RLS to conversation members).
-- Message ids are generated by the client so a retried send is idempotent.

create table public.conversations (
    id uuid primary key default gen_random_uuid(),
    -- The pair is stored ordered (user_a < user_b) so a pair has one conversation.
    user_a uuid not null references public.profiles (id) on delete cascade,
    user_b uuid not null references public.profiles (id) on delete cascade,
    created_at timestamptz not null default now(),
    last_message_at timestamptz,
    constraint conversations_ordered_pair check (user_a < user_b),
    constraint conversations_unique_pair unique (user_a, user_b)
);

create index conversations_user_b_idx on public.conversations (user_b);

create table public.conversation_members (
    conversation_id uuid not null references public.conversations (id) on delete cascade,
    user_id uuid not null references public.profiles (id) on delete cascade,
    last_read_at timestamptz,
    primary key (conversation_id, user_id)
);

create index conversation_members_user_idx on public.conversation_members (user_id);

create table public.messages (
    id uuid primary key,
    conversation_id uuid not null references public.conversations (id) on delete cascade,
    sender_id uuid not null references public.profiles (id) on delete cascade,
    body text not null check (char_length(btrim(body)) between 1 and 2000),
    created_at timestamptz not null default now()
);

create index messages_conversation_created_idx on public.messages (conversation_id, created_at desc, id desc);
create index messages_sender_idx on public.messages (sender_id);

create function public.is_conversation_member(p_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1 from public.conversation_members
        where conversation_id = p_conversation_id and user_id = auth.uid()
    ) and exists (select 1 from public.current_student())
$$;

revoke all on function public.is_conversation_member(uuid) from public, anon;
grant execute on function public.is_conversation_member(uuid) to authenticated;

alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

-- Read access for members only; this is also what Realtime uses to decide who
-- receives a change. Writes go through the functions below.
create policy conversations_select_member on public.conversations
    for select to authenticated
    using ((select public.is_conversation_member(id)));

create policy conversation_members_select_member on public.conversation_members
    for select to authenticated
    using ((select public.is_conversation_member(conversation_id)));

create policy messages_select_member on public.messages
    for select to authenticated
    using ((select public.is_conversation_member(conversation_id)));

-- API -----------------------------------------------------------------------------

-- Returns the conversation with another approved student, creating it once.
create function public.start_conversation(p_other_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_me uuid := auth.uid();
    v_a uuid;
    v_b uuid;
    v_id uuid;
begin
    if not exists (select 1 from public.current_student()) then
        raise exception using errcode = 'P0001', message = 'approved_student_required';
    end if;
    if p_other_user_id is null or p_other_user_id = v_me or not exists (
        select 1 from public.profiles where id = p_other_user_id and account_status = 'APPROVED'
    ) then
        raise exception using errcode = 'P0001', message = 'recipient_not_available';
    end if;

    v_a := least(v_me, p_other_user_id);
    v_b := greatest(v_me, p_other_user_id);

    insert into public.conversations (user_a, user_b) values (v_a, v_b)
    on conflict (user_a, user_b) do nothing
    returning id into v_id;

    if v_id is null then
        select id into v_id from public.conversations where user_a = v_a and user_b = v_b;
    else
        insert into public.conversation_members (conversation_id, user_id)
        values (v_id, v_a), (v_id, v_b);
    end if;
    return v_id;
end;
$$;

-- Idempotent: resending the same message id returns without a duplicate.
create function public.send_message(p_conversation_id uuid, p_message_id uuid, p_body text)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_body text := btrim(coalesce(p_body, ''));
    v_created timestamptz;
    v_other uuid;
begin
    if not public.is_conversation_member(p_conversation_id) then
        raise exception using errcode = 'P0001', message = 'conversation_not_found';
    end if;
    if p_message_id is null or char_length(v_body) not between 1 and 2000 then
        raise exception using errcode = 'P0001', message = 'invalid_message';
    end if;

    select created_at into v_created
    from public.messages
    where id = p_message_id and conversation_id = p_conversation_id and sender_id = auth.uid();
    if found then
        return v_created;
    end if;

    -- The other member must still be an approved student.
    select m.user_id into v_other
    from public.conversation_members m
    join public.profiles p on p.id = m.user_id and p.account_status = 'APPROVED'
    where m.conversation_id = p_conversation_id and m.user_id <> auth.uid();
    if v_other is null then
        raise exception using errcode = 'P0001', message = 'recipient_not_available';
    end if;

    if (select count(*) from public.messages
        where sender_id = auth.uid() and created_at > now() - interval '1 minute') >= 30 then
        raise exception using errcode = 'P0001', message = 'rate_limited';
    end if;

    insert into public.messages (id, conversation_id, sender_id, body)
    values (p_message_id, p_conversation_id, auth.uid(), v_body)
    returning created_at into v_created;

    update public.conversations set last_message_at = v_created where id = p_conversation_id;
    -- Sending implies having read everything before it.
    update public.conversation_members set last_read_at = v_created
    where conversation_id = p_conversation_id and user_id = auth.uid();
    return v_created;
exception
    when unique_violation then
        -- Same id used for a different conversation or by someone else.
        raise exception using errcode = 'P0001', message = 'invalid_message';
end;
$$;

create function public.mark_conversation_read(p_conversation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if not public.is_conversation_member(p_conversation_id) then
        raise exception using errcode = 'P0001', message = 'conversation_not_found';
    end if;
    update public.conversation_members
    set last_read_at = greatest(coalesce(last_read_at, '-infinity'), now())
    where conversation_id = p_conversation_id and user_id = auth.uid();
end;
$$;

create function public.list_conversations()
returns table (
    conversation_id uuid,
    other_user_id uuid,
    other_full_name text,
    other_username text,
    other_university text,
    last_message_body text,
    last_message_at timestamptz,
    last_message_is_mine boolean,
    unread_count integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not exists (select 1 from public.current_student()) then
        raise exception using errcode = 'P0001', message = 'approved_student_required';
    end if;
    return query
    select c.id, o.id, o.full_name, o.username, u.name,
           lm.body, lm.created_at, lm.sender_id = auth.uid(),
           (select count(*)::integer from public.messages x
            where x.conversation_id = c.id and x.sender_id <> auth.uid()
              and x.created_at > coalesce(me.last_read_at, '-infinity'))
    from public.conversation_members me
    join public.conversations c on c.id = me.conversation_id
    join public.profiles o on o.id = case when c.user_a = auth.uid() then c.user_b else c.user_a end
    left join public.universities u on u.id = o.university_id
    left join lateral (
        select m.body, m.created_at, m.sender_id
        from public.messages m
        where m.conversation_id = c.id
        order by m.created_at desc, m.id desc
        limit 1
    ) lm on true
    where me.user_id = auth.uid()
    order by coalesce(c.last_message_at, c.created_at) desc
    limit 200;
end;
$$;

-- Newest first, keyset-paginated. read_by_other drives the "read" receipt.
create function public.list_messages(
    p_conversation_id uuid,
    p_before_created_at timestamptz default null,
    p_before_id uuid default null,
    p_limit integer default 50
)
returns table (
    id uuid,
    sender_id uuid,
    body text,
    created_at timestamptz,
    is_mine boolean,
    read_by_other boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_other_read timestamptz;
begin
    if not public.is_conversation_member(p_conversation_id) then
        raise exception using errcode = 'P0001', message = 'conversation_not_found';
    end if;
    select last_read_at into v_other_read
    from public.conversation_members
    where conversation_id = p_conversation_id and user_id <> auth.uid();

    return query
    select m.id, m.sender_id, m.body, m.created_at, m.sender_id = auth.uid(),
           m.sender_id = auth.uid() and v_other_read is not null and v_other_read >= m.created_at
    from public.messages m
    where m.conversation_id = p_conversation_id
      and (p_before_created_at is null
           or (m.created_at, m.id) < (p_before_created_at, coalesce(p_before_id, 'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid)))
    order by m.created_at desc, m.id desc
    limit least(greatest(coalesce(p_limit, 50), 1), 100);
end;
$$;

do $$
declare
    f text;
begin
    foreach f in array array[
        'public.start_conversation(uuid)',
        'public.send_message(uuid, uuid, text)',
        'public.mark_conversation_read(uuid)',
        'public.list_conversations()',
        'public.list_messages(uuid, timestamptz, uuid, integer)'
    ] loop
        execute format('revoke all on function %s from public, anon', f);
        execute format('grant execute on function %s to authenticated', f);
    end loop;
end;
$$;

-- Realtime: stream inserts of messages and read-receipt updates to members.
alter publication supabase_realtime add table public.messages, public.conversation_members;
