-- Generated by scripts/generate-legal-migration.py from docs/legal/*.md. Do not edit by hand.
-- Version 1 of every legal text (drafts awaiting legal review; placeholders in [brackets]).

insert into public.legal_documents (doc_type, version, title, content) values ('acik_riza_pazarlama_bildirim', 1, 'Açık Rıza Metni — Anlık Bildirim ile Kampanya ve Duyuru İletileri', $legal$# Açık Rıza Metni — Anlık Bildirim ile Kampanya ve Duyuru İletileri

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

Bu metin Aydınlatma Metni'nden ayrıdır ve isteğe bağlıdır. **Onay vermesen de KampüsAğı'nın tüm temel özelliklerini kullanabilirsin.**

[VERİ SORUMLUSU UNVANI] tarafından, cihazımın bildirim belirtecinin (FCM token); Premium indirimleri, yeni özellikler ve kampanyalar gibi tanıtım içerikli anlık bildirimlerin bana gönderilmesi amacıyla işlenmesine ve bu amaçla Google LLC / Google Ireland Ltd. (Firebase Cloud Messaging) hizmetine aktarılmasına **açık rıza ve onay** veriyorum.

- Mesaj geldi, belgen onaylandı gibi **işlemsel bildirimler** bu onaydan bağımsızdır ve ayrı bir bildirim kanalından gelir. Bunları telefonunun bildirim ayarlarından kapatabilirsin.
- Onayımı dilediğim an **Ayarlar → Gizlilik ve KVKK → Rızalarım** ekranından geri alabilirim; her kampanya bildirimi bu ekrana götüren bir "bildirimleri kapat" yolu içerir. Geri alma anında etkili olur.
- Verilen ve geri alınan onaylar, metnin sürümüyle birlikte ispat amacıyla saklanır.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('acik_riza_pazarlama_eposta', 1, 'Açık Rıza Metni — E-posta ile Kampanya ve Duyuru İletileri', $legal$# Açık Rıza Metni — E-posta ile Kampanya ve Duyuru İletileri

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

Bu metin Aydınlatma Metni'nden ayrıdır ve isteğe bağlıdır. **Onay vermesen de KampüsAğı'nın tüm temel özelliklerini kullanabilirsin.**

[VERİ SORUMLUSU UNVANI] ("Veri sorumlusu") tarafından, e-posta adresimin ve adımın; Premium indirimleri, yeni özellikler, kampüs etkinlikleri ve benzeri kampanya ve tanıtım içerikli ticari elektronik iletilerin bana e-posta ile gönderilmesi amacıyla işlenmesine ve bu amaçla e-posta gönderim hizmeti sağlayıcısı Resend Inc.'e (İrlanda, AB) aktarılmasına, 6698 sayılı Kanun ve 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun kapsamında **açık rıza ve onay** veriyorum.

- Hizmetle ilgili zorunlu bildirimler (şifre sıfırlama, hesap ve güvenlik bildirimleri) bu onaydan bağımsızdır.
- Onayımı dilediğim an, gerekçe göstermeden ve ücretsiz olarak **Ayarlar → Gizlilik ve KVKK → Rızalarım** ekranından veya her e-postadaki **"Abonelikten çık"** bağlantısıyla geri alabilirim. Geri alma anında etkili olur.
- Verilen ve geri alınan onaylar, onayın verildiği metnin sürümüyle birlikte ispat amacıyla saklanır.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('aydinlatma_metni', 1, 'KampüsAğı Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni', $legal$# KampüsAğı Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni

> **TASLAK — AVUKAT ONAYI GEREKLİ.** Köşeli parantez içindeki alanlar veri sorumlusu tarafından doldurulmadan bu metin yürürlüğe girmez.

Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu'nun ("KVKK") 10. maddesi ve Aydınlatma Yükümlülüğünün Yerine Getirilmesinde Uyulacak Usul ve Esaslar Hakkında Tebliğ uyarınca, KampüsAğı mobil uygulaması ve kampusagi web sitesi ("Platform") kullanıcılarını bilgilendirmek için hazırlanmıştır.

## 1. Veri sorumlusu

- Unvan: [VERİ SORUMLUSU UNVANI]
- Adres: [ADRES]
- MERSİS / Vergi No: [MERSİS NO] / [VERGİ DAİRESİ VE NO]
- KEP adresi: [KEP]
- E-posta: [İLETİŞİM E-POSTASI]
- VERBİS kayıt numarası (varsa): [VERBİS KAYIT NO]

## 2. Hangi kişisel verileri, hangi amaçla ve hangi hukuki sebeple işliyoruz?

| Veri kategorisi | İşlenen veriler | Amaç | Hukuki sebep (KVKK md.5) | Toplama yöntemi |
|---|---|---|---|---|
| Kimlik | Ad soyad, kullanıcı adı | Hesap oluşturma, Platform'da kim olduğunun gösterilmesi | Sözleşmenin kurulması ve ifası (md.5/2-c) | Uygulamadaki profil formu (elektronik) |
| Yaş beyanı | Doğum tarihi | Yalnızca 18 yaş kontrolü; kaydedilmez | Sözleşmenin kurulması (md.5/2-c) | Kayıt formu (elektronik) |
| İletişim | E-posta adresi | Giriş, e-posta doğrulama, şifre sıfırlama, hizmet bildirimleri | Sözleşmenin ifası (md.5/2-c) | Kayıt formu (elektronik) |
| Öğrenci doğrulama belgesi | Öğrenci belgesi (PDF), belgenin SHA-256 özeti, üniversite, bölüm, doğrulama tarihi ve doğrulayan yetkili | Yalnızca öğrencilik durumunun doğrulanması | Sözleşmenin ifası (md.5/2-c), meşru menfaat (md.5/2-f: Platform'un yalnızca öğrencilere açık olması) | Uygulamaya yüklenen dosya (elektronik) |
| Profil | Biyografi, profil fotoğrafı, soyad görünürlük tercihi, rozetler | Profilinin diğer öğrencilere gösterilmesi | Sözleşmenin ifası (md.5/2-c) | Uygulama (elektronik) |
| Kullanıcı içeriği | Gönderiler, fotoğraflar, anketler ve oylar, etkinlikler ve katılımlar, ilanlar, yorumlar, beğeniler, kaydedilenler, ihtiyaç ilanları (başlık, açıklama, etiketler, elle yazılan yer, tarih), ders notları (PDF), grup ve kanal mesajları | Topluluk hizmetlerinin sunulması | Sözleşmenin ifası (md.5/2-c) | Uygulama (elektronik) |
| Mesajlar | Birebir ve grup mesajları, okundu bilgisi | Mesajlaşma hizmeti | Sözleşmenin ifası (md.5/2-c) | Uygulama (elektronik) |
| Eşleşme | İhtiyaç ilanlarının kategori, etiket, kelime, zaman ve yer bilgisi | Benzer ihtiyacı olan öğrencilerin otomatik olarak önerilmesi | Sözleşmenin ifası (md.5/2-c) | Otomatik analiz (bkz. 4. bölüm) |
| İşlem güvenliği ve log | Giriş, çıkış, başarısız giriş ve şifre sıfırlama kayıtları; IP adresi; cihaz bilgisi; uygulama sürümü; onay kayıtları; engelleme ve şikâyet kayıtları; uygulama hata raporları; uygulamayı açtığın günler | Hesap güvenliği, kötüye kullanımın önlenmesi, 5651 sayılı Kanun kapsamındaki yükümlülükler, yetkili mercilerin talepleri, hata giderme | Kanunlarda açıkça öngörülme (md.5/2-a), hukuki yükümlülük (md.5/2-ç), meşru menfaat (md.5/2-f) | Sunucu ve uygulama tarafından otomatik |
| Cihaz bilgisi | Bildirim belirteci (FCM token), platform | Anlık bildirim gönderimi | Sözleşmenin ifası (md.5/2-c) | Uygulama (otomatik) |
| Ödeme / abonelik durumu | Google Play satın alma jetonu, ürün, abonelik bitiş tarihi, sipariş numarası, Google'ın bildirdiği fiyat, hediye ve promosyon kodu kayıtları | Premium üyeliğin sağlanması, muhasebe ve tüketici mevzuatı yükümlülükleri | Sözleşmenin ifası (md.5/2-c), hukuki yükümlülük (md.5/2-ç) | Google Play (elektronik). Kart bilgilerine erişmiyoruz. |
| Pazarlama tercihleri | E-posta ve bildirim izinleri ve geçmişi | Kampanya ve duyuru iletileri | Açık rıza (md.5/1) | Uygulama ayarları |
| Başvuru ve talepler | Veri sahibi başvuruları, telif bildirimleri, yanıtlar | Başvuruların yanıtlanması | Hukuki yükümlülük (md.5/2-ç), hakkın tesisi ve korunması (md.5/2-e) | Uygulama, web formu, e-posta |

Din, mezhep, etnik köken, siyasi görüş, sağlık, cinsel hayat, sendika üyeliği, biyometrik veri gibi özel nitelikli kişisel verileri (KVKK md.6) **istemiyoruz ve işlemiyoruz**. Bu tür bilgileri gönderilerine, etiketlerine veya mesajlarına yazmamanı rica ederiz. Öğrenci belgende bulunabilecek T.C. kimlik numarası, fotoğraf veya adres gibi bilgiler ayrıca kaydedilmez, okunmaz (OCR yapılmaz) ve belge en geç doğrulama kararından 30 gün sonra silinir.

Konum izni (GPS) istemiyoruz. Yer bilgisi yalnızca senin elle yazdığın semt, kampüs veya ilçedir.

## 3. Kişisel verileri kimlere ve hangi amaçla aktarıyoruz?

| Alıcı | Aktarılan veri | Amaç | Ülke |
|---|---|---|---|
| Supabase Inc. (veri işleyen) | Platform'daki tüm veriler | Veritabanı, kimlik doğrulama, dosya depolama ve sunucu fonksiyonlarının barındırılması | [SUPABASE BÖLGESİ] (yurt dışı) |
| Google LLC / Google Ireland Ltd. (Firebase Cloud Messaging) | Bildirim belirteci, bildirim türü | Anlık bildirim iletimi (bildirim metni mesaj içeriği taşımaz) | ABD / AB |
| Google Ireland Ltd. / Google LLC (Google Play) | Satın alma bilgileri | Abonelik ödemesi ve doğrulaması | AB / ABD |
| Resend Inc. (veri işleyen) | E-posta adresi, e-posta içeriği | Hizmet ve (izin verdiysen) pazarlama e-postalarının gönderimi | İrlanda (AB) |
| Vercel Inc. (veri işleyen) | Web sitesi ziyaretinde IP adresi ve tarayıcı bilgisi; yönetim paneli oturumları | Web sitesi ve yönetim panelinin barındırılması | ABD / AB |
| Cloudflare Inc. | E-posta yönlendirmede iletişim adresine yazılan e-postalar | Alan adı ve e-posta yönlendirme | Küresel |
| Yetkili kamu kurum ve kuruluşları, yargı mercileri | Talep edilen kayıtlar | Kanuni yükümlülükler (5651 sayılı Kanun dahil) | Türkiye |

Yurt dışına aktarım, KVKK md.9 uyarınca standart sözleşme (veya ilgili mevzuatta öngörülen diğer uygun güvenceler) ile yapılır; standart sözleşmeler imzalandıktan sonra 5 iş günü içinde Kişisel Verileri Koruma Kurumu'na bildirilir. Ayrıntı: Gizlilik Politikası.

Diğer kullanıcılar senin profilini, gönderilerini ve sana yazdıklarını Platform kuralları çerçevesinde görür. E-posta adresin diğer kullanıcılara hiçbir zaman gösterilmez; soyadın ise yalnızca ayarlardan izin verirsen gösterilir.

## 4. Otomatik analiz (eşleşme)

İhtiyaç ilanları, aynı üniversite ve aynı kategorideki diğer ilanlarla kural tabanlı bir yöntemle karşılaştırılır: ortak etiketler (%50), ortak kelimeler (%25), zaman yakınlığı (%15) ve yer benzerliği (%10). Yapay zekâ kullanılmaz. Sonuç yalnızca bir öneridir; hiçbir hukuki sonuç doğurmaz. Uygulamada her eşleşme için "Bu eşleşme neden önerildi?" açıklamasını görebilir ve **itiraz edebilirsin** (KVKK md.11/1-g). İtiraz ettiğin eşleşme sana bir daha gösterilmez.

## 5. Saklama süreleri

Kişisel veriler, Kişisel Veri Saklama ve İmha Politikası'nda yazan sürelerce saklanır ve süre dolunca otomatik olarak silinir veya anonim hale getirilir. Özetle: öğrenci belgesi karardan sonra en geç 30 gün; hesap silme talebinde 30 günlük geri alma süresinden sonra hesap verileri; 5651 kapsamındaki trafik kayıtları 2 yıl; onay kayıtları ve yönetici işlem kayıtları ispat amacıyla 10 yıl.

## 6. KVKK md.11 kapsamındaki hakların

Veri sorumlusuna başvurarak:

1. Kişisel verilerinin işlenip işlenmediğini öğrenme,
2. İşlenmişse buna ilişkin bilgi talep etme,
3. İşlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme,
4. Yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme,
5. Eksik veya yanlış işlenmişse düzeltilmesini isteme,
6. KVKK md.7'deki şartlar çerçevesinde silinmesini veya yok edilmesini isteme,
7. 5. ve 6. bentlerdeki işlemlerin, verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme,
8. İşlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle aleyhine bir sonucun ortaya çıkmasına itiraz etme,
9. Kanuna aykırı işleme sebebiyle zarara uğraman hâlinde zararın giderilmesini talep etme

haklarına sahipsin.

Başvurunu uygulamadaki **Ayarlar → Gizlilik ve KVKK → Başvuru oluştur** bölümünden, [İLETİŞİM E-POSTASI] adresine kayıtlı e-posta adresinden, [KEP] adresine KEP ile veya [ADRES] adresine yazılı olarak yapabilirsin. Başvurular en geç 30 gün içinde ücretsiz yanıtlanır (Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ). Verilerini **Verilerimi indir** ile kendin indirebilir, **Hesabımı sil** ile hesabını silebilirsin.

## 7. Log (işlem kaydı) bilgilendirmesi

Hesabının güvenliği ve 5651 sayılı Kanun kapsamındaki yükümlülüklerimiz gereği giriş, çıkış, başarısız giriş ve şifre sıfırlama işlemlerin; IP adresin, cihaz bilgin ve işlem zamanı kayıt altına alınır. Bu kayıtlar değiştirilemez şekilde saklanır, yalnızca yetkili personel tarafından güvenlik ve yasal talepler için görüntülenebilir ve her görüntüleme ayrıca kaydedilir.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('basvuru_formu', 1, 'Veri Sahibi Başvuru Formu', $legal$# Veri Sahibi Başvuru Formu

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

6698 sayılı Kanun md.11 ve md.13 ile Veri Sorumlusuna Başvuru Usul ve Esasları Hakkında Tebliğ uyarınca, kişisel verilerinle ilgili taleplerini bu formla iletebilirsin.

## Başvuru yolları

1. **Uygulama içinden:** Ayarlar → Gizlilik ve KVKK → Başvuru oluştur. Hesabınla giriş yaptığın için kimliğin ayrıca doğrulanmış olur; başvuru numarası hemen verilir.
2. **E-posta:** Platform'a kayıtlı e-posta adresinden [İLETİŞİM E-POSTASI] adresine.
3. **KEP:** [KEP]
4. **Yazılı:** [ADRES] adresine ıslak imzalı dilekçe.

## Başvuruda bulunması gerekenler

- Ad, soyad ve (yazılı başvuruda) imza
- T.C. vatandaşları için T.C. kimlik numarası; yabancılar için uyruk, pasaport veya kimlik numarası (yalnızca yazılı/KEP başvurularında kimlik doğrulama için)
- Tebligata esas yerleşim yeri veya iş yeri adresi
- Varsa e-posta, telefon veya faks numarası
- Talep konusu

## Talep türleri

- [ ] Verilerimin işlenip işlenmediğini öğrenmek ve bilgi talep etmek
- [ ] İşleme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenmek
- [ ] Verilerimin aktarıldığı üçüncü kişileri öğrenmek
- [ ] Eksik veya yanlış verilerin düzeltilmesini istemek
- [ ] Verilerimin silinmesini veya yok edilmesini istemek
- [ ] Düzeltme / silme işlemlerinin aktarılan üçüncü kişilere bildirilmesini istemek
- [ ] Otomatik analiz sonucu aleyhime bir sonuca itiraz etmek
- [ ] Kanuna aykırı işleme nedeniyle uğradığım zararın giderilmesini talep etmek

## Yanıt

Başvurun, talebin niteliğine göre en kısa sürede ve **en geç 30 gün içinde ücretsiz** sonuçlandırılır. İşlemin ayrıca bir maliyet gerektirmesi hâlinde Kurul'ca belirlenen tarife uygulanabilir. Yanıt, başvurunun geldiği kanaldan veya uygulamadaki **Başvurularım** ekranından iletilir. Başvurunun reddedilmesi, cevabın yetersiz bulunması veya süresinde cevap verilmemesi hâlinde Kişisel Verileri Koruma Kurulu'na şikâyette bulunabilirsin.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('cerez_sdk_politikasi', 1, 'Çerez ve Üçüncü Taraf SDK Politikası', $legal$# Çerez ve Üçüncü Taraf SDK Politikası

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

## Mobil uygulamadaki üçüncü taraf yazılım bileşenleri (SDK)

| SDK | Sağlayıcı | Amaç | Topladığı veri | Rıza |
|---|---|---|---|---|
| supabase-kt | Supabase Inc. | Giriş, veritabanı, dosya, gerçek zamanlı güncelleme | Oturum belirteci, gönderdiğin istekler, IP adresi (sunucu tarafında) | Gerekmez (hizmetin sunulması) |
| Firebase Cloud Messaging | Google LLC | Anlık bildirim | FCM belirteci, uygulama örneği kimliği | Gerekmez (işlemsel bildirim); kampanya bildirimleri için ayrı açık rıza |
| Google Play Billing | Google LLC | Premium abonelik satın alma | Satın alma bilgileri | Gerekmez (sözleşmenin ifası) |
| AndroidX / Jetpack, Kotlin Coroutines, Hilt, Ktor | Google, JetBrains | Uygulama altyapısı | Kişisel veri toplamaz | — |

**Kullanılmayanlar:** Firebase Analytics, Google Analytics, Crashlytics, reklam SDK'ları ve reklam kimliği. Çökme raporları kendi sunucumuza, kişisel veri içermeden (ad, e-posta, mesaj içeriği yok; yalnızca anonim kullanıcı kimliği, cihaz modeli, sürüm ve hata yığını) gönderilir. İleride analitik bir araç eklenirse varsayılan olarak kapalı olacak ve yalnızca ayrı açık rızanla açılacaktır.

## Web sitesi

- Web sitesi ve yönetim paneli Vercel üzerinde barındırılır. Ziyaret sırasında IP adresi ve tarayıcı bilgisi barındırma sağlayıcısının sunucu kayıtlarında işlenir.
- Web sitesinde **reklam veya analitik çerezi kullanılmaz.**
- Yönetim paneline ve hesap silme sayfasına giriş yapıldığında, oturumu sürdürmek için zorunlu oturum verisi tarayıcının yerel depolamasında tutulur (zorunlu, rıza gerektirmez). Çıkış yapıldığında silinir.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('cocuk_guvenligi', 1, 'Çocuk Güvenliği Standartları', $legal$# Çocuk Güvenliği Standartları

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

KampüsAğı, çocukların cinsel istismarına ve istismarı içeren materyallere (CSAE / CSAM) karşı **sıfır tolerans** uygular. Bu metin Google Play'in çocuk güvenliği standartları politikası kapsamında yayımlanmıştır.

## Yasaklar

- Reşit olmayanları cinselleştiren, istismar eden veya tehlikeye atan her türlü metin, görsel, bağlantı ve mesaj.
- Reşit olmayanlarla cinsel amaçlı iletişim kurma, onları kandırma veya yönlendirme (grooming).
- Bu tür materyalin talep edilmesi, paylaşılması veya nereden bulunabileceğinin söylenmesi.

## Nasıl önlüyoruz?

- Hizmet yalnızca 18 yaşını doldurmuş ve öğrenci belgesi yetkili personelce onaylanmış kişilere açıktır.
- Her gönderi, yorum, mesaj, grup ve kanal mesajı, ders notu ve kullanıcı uygulama içinden tek dokunuşla şikâyet edilebilir; kişiler engellenebilir.
- Şikâyetler öncelikle incelenir; ihlal içeren içerik kaldırılır ve hesap kalıcı olarak kapatılır.
- CSAM tespit edildiğinde içerik kaldırılır, gerekli kayıtlar saklanır ve yetkili makamlara (Emniyet Genel Müdürlüğü Siber Suçlarla Mücadele birimi, gerektiğinde NCMEC) bildirilir.

## Bildirmek için

Uygulamadaki **Şikâyet et** seçeneğini kullan ya da [İLETİŞİM E-POSTASI] adresine yaz. Acil bir tehlike varsa önce 112'yi ara. Bu adres, çocuk güvenliği bildirimleri ve Google Play ile iletişim için belirlenmiş sorumlu kişiye ulaşır.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('gizlilik_politikasi', 1, 'KampüsAğı Gizlilik Politikası', $legal$# KampüsAğı Gizlilik Politikası

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

Bu politika Google Play ve App Store gizlilik politikası şartları için hazırlanmıştır ve KampüsAğı Aydınlatma Metni ile birlikte okunmalıdır. İkisi arasında fark varsa Aydınlatma Metni esas alınır.

- Veri sorumlusu: [VERİ SORUMLUSU UNVANI], [ADRES]
- İletişim: [İLETİŞİM E-POSTASI] · KEP: [KEP]

## 1. Topladığımız veriler

- **Hesap:** e-posta adresi, şifre (yalnızca şifrelenmiş özeti, Supabase Auth tarafından), ad soyad, kullanıcı adı, üniversite, bölüm.
- **Yaş:** doğum tarihin yalnızca 18 yaş kontrolü için kullanılır, saklanmaz.
- **Öğrenci doğrulama:** öğrenci belgesi (PDF). Belge yalnızca yetkili doğrulama personeline, kısa süreli ve her açılışı kayıt altına alınan bir bağlantıyla gösterilir; karar verildikten sonra en geç 30 gün içinde silinir. Kalıcı olarak yalnızca doğrulandığın, tarih, doğrulayan yetkili ve belgenin SHA-256 özeti tutulur.
- **Profil:** biyografi, profil fotoğrafı, soyad görünürlük tercihi.
- **İçerik:** gönderiler, fotoğraflar, anketler, etkinlikler, ilanlar, yorumlar, beğeniler, ihtiyaç ilanları, ders notları, birebir/grup/kanal mesajları.
- **Kayıtlar (log):** giriş, çıkış, başarısız giriş ve şifre sıfırlama zamanı, IP adresi, cihaz modeli, işletim sistemi ve uygulama sürümü; onay/rıza kayıtları; şikâyet ve engellemeler.
- **Hata raporları:** uygulama çöktüğünde cihaz modeli, Android sürümü, uygulama sürümü ve hata yığını. Ad, e-posta veya mesaj içeriği hata raporlarına yazılmaz.
- **Bildirim belirteci:** anlık bildirim göndermek için Firebase Cloud Messaging belirteci.
- **Satın alma:** Google Play abonelik bilgisi (ürün, süre, sipariş numarası, fiyat). Kart bilgilerine erişmiyoruz.
- **Kullanım:** yalnızca uygulamayı hangi gün açtığın bilgisi (günde tek kayıt, başka davranış verisi toplanmaz).

**Toplamadıklarımız:** konum (GPS), rehber, mikrofon, kamera kaydı (fotoğraf yalnızca senin seçtiğin görseldir), reklam kimliği. Platform'da reklam yoktur; kullanıcıları başka uygulama ve sitelerde **izlemiyoruz** (App Tracking Transparency kapsamında takip yapılmaz). Analitik veya reklam SDK'sı kullanılmaz.

## 2. Kullanım amaçları

Hizmeti sunmak, öğrenciliği doğrulamak, hesabını ve topluluğu korumak, yasal yükümlülükleri (5651, 6698, 6502 sayılı Kanunlar) yerine getirmek, şikâyetleri incelemek ve yalnızca açık rızan varsa kampanya iletileri göndermek.

## 3. Paylaşım ve yurt dışı aktarım

Verilerin satılmaz. Hizmet sağlayıcılarımız: Supabase (veritabanı ve dosya depolama, [SUPABASE BÖLGESİ]), Google Firebase Cloud Messaging (bildirim), Google Play (ödeme), Resend (e-posta, İrlanda), Vercel (web sitesi), Cloudflare (alan adı ve e-posta yönlendirme). Bu sağlayıcılar yurt dışında bulunduğundan aktarım KVKK md.9 uyarınca standart sözleşmelerle yapılır. Yetkili makamların hukuka uygun talepleri saklıdır.

## 4. Güvenlik

Tüm bağlantılar HTTPS (TLS) ile şifrelenir; veriler barındırma sağlayıcısında şifreli diskte saklanır. Veritabanında satır düzeyinde erişim kuralları uygulanır; her kullanıcı yalnızca görmesine izin verilen veriye erişir. Yönetici hesapları iki adımlı doğrulama ile korunur, rollere ayrılmıştır (belge doğrulama, içerik moderasyonu, KVKK) ve her yönetici işlemi gerekçesiyle, değiştirilemez şekilde kayıt altına alınır. Yöneticiler özel mesajlarını okuyamaz; yalnızca şikâyet edilen bir mesaj ve yakın bağlamı, kayıt altına alınarak incelenebilir.

## 5. Saklama ve silme

Saklama süreleri Kişisel Veri Saklama ve İmha Politikası'ndadır. **Hesabını uygulamadan (Ayarlar → Gizlilik ve KVKK → Hesabımı sil) veya web sitemizdeki hesap silme sayfasından silebilirsin.** 30 günlük geri alma süresinden sonra hesabın ve içeriklerin kalıcı olarak silinir; yasal saklama zorunluluğu olan kayıtlar profilinden ayrılarak yasal süre boyunca tutulur.

## 6. Hakların

KVKK md.11 kapsamındaki hakların Aydınlatma Metni'nde yazılıdır. Verilerini uygulamadan **Verilerimi indir** ile indirebilir, rızalarını **Rızalarım** ekranından geri alabilir, **Başvuru oluştur** ile başvuru yapabilirsin. Kişisel Verileri Koruma Kurulu'na şikâyet hakkın saklıdır.

## 7. Çocuklar

Platform 18 yaşından küçükler için değildir; 18 yaşından küçük olduğu anlaşılan hesaplar kapatılır.

## 8. Değişiklikler

Bu politikanın her sürümü saklanır; önemli değişikliklerde uygulamaya bir sonraki girişinde bilgilendirilirsin.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('kullanim_kosullari', 1, 'KampüsAğı Kullanım Koşulları ve Üyelik Sözleşmesi', $legal$# KampüsAğı Kullanım Koşulları ve Üyelik Sözleşmesi

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

Bu sözleşme, [VERİ SORUMLUSU UNVANI] ("KampüsAğı", "biz") ile KampüsAğı mobil uygulamasına ve web sitesine ("Platform") üye olan kullanıcı ("sen") arasındadır. Kayıt olurken bu koşulları kabul etmeden üyelik oluşmaz. Kişisel verilerinin nasıl işlendiği Aydınlatma Metni'nde ve Gizlilik Politikası'nda anlatılır.

İletişim: [İLETİŞİM E-POSTASI] · [ADRES] · [KEP]

## 1. Üyelik şartları

1. **18 yaşını doldurmuş olmalısın.** Kayıt sırasında doğum tarihin yalnızca bu kontrol için alınır ve saklanmaz. 18 yaşından küçükler üye olamaz.
2. Platform, Türkiye'deki yükseköğretim kurumlarında öğrenim gören kişiler içindir. Topluluk özelliklerini kullanmak için öğrenci belgenin yetkili personelce onaylanması gerekir.
3. **Gerçek kimliğinle** kayıt olmalısın. Başkası adına, sahte veya yanıltıcı bilgiyle hesap açmak yasaktır. Her kişi tek hesap açabilir.
4. Hesabının ve şifrenin güvenliğinden sen sorumlusun; hesabının yetkisiz kullanıldığını fark edersen bize hemen bildir.

## 2. Hizmetin kapsamı

Platform; profil, akış (metin, fotoğraf, anket, etkinlik, ilan), birebir ve grup sohbeti, çalışma grupları, Premium kanallar, ders notu paylaşımı, rozetler ve ihtiyaç ilanlarının etiketlere göre eşleştirilmesi özelliklerini sunar. Özellikler zaman içinde değişebilir.

## 3. Yasak içerik ve davranışlar

Topluluk Kuralları bu sözleşmenin ayrılmaz parçasıdır. Özetle; taciz, tehdit, nefret söylemi ve ayrımcılık, başkalarının kişisel verilerini (telefon, adres, belge, fotoğraf) izinsiz paylaşmak, cinsel içerik, reşit olmayanları içeren her türlü istismar içeriği, şiddeti veya yasa dışı faaliyeti özendirme, dolandırıcılık, spam, sahte hesap ve telif hakkı ihlali yasaktır.

## 4. Paylaştığın içerik

1. Paylaştığın içeriğin hukuki sorumluluğu sana aittir; içeriğin sahibi olmalı veya paylaşma iznine sahip olmalısın.
2. İçeriğini Platform'da gösterebilmemiz için bize sınırlı, ücretsiz, münhasır olmayan ve devredilemez bir kullanım izni verirsin. İçeriği silmen veya hesabını kapatman hâlinde bu izin sona erer (yasal saklama yükümlülükleri saklıdır).
3. Ders notu yüklerken, içeriğin hak sahibi olduğunu veya paylaşım iznin bulunduğunu beyan edersin. Hocalara ait sınav sorularını veya telifli kitap sayfalarını izinsiz paylaşamazsın. Ayrıntılar: Telif Hakkı ve İçerik Kaldırma Politikası.

## 5. Aracılık hizmeti olmadığı

Ev arkadaşı, eşya, ders çalışma ve benzeri **ihtiyaç ilanları, al-sat ilanları ve etkinlikler kullanıcılar arasındadır**. KampüsAğı bu ilişkilerde aracı, emlakçı, satıcı, kiraya veren veya organizatör değildir; kullanıcılar arasında yapılan anlaşmaların **tarafı değildir**, ödeme almaz, teslimatı, ilanların doğruluğunu veya kişilerin güvenilirliğini garanti etmez. Buluşmalarda ve anlaşmalarda dikkatli ol; şüpheli ilanları şikâyet et.

## 6. Eşleştirme

Eşleşmeler kural tabanlı otomatik bir analizdir (ortak etiket, kelime, zaman, yer). Yalnızca öneri niteliğindedir, kişi hakkında bir değerlendirme değildir. Eşleşmeye itiraz edebilirsin. Din, mezhep, etnik köken, siyasi görüş, sağlık veya cinsel yönelim gibi özelliklere göre etiket veya filtre kullanılamaz.

## 7. Premium

Premium abonelik yalnızca Google Play üzerinden satın alınır. Fiyat, süre, otomatik yenileme ve iptal koşulları Premium Ön Bilgilendirme Formu ve Mesafeli Sözleşme'de yer alır.

## 8. Şikâyet, moderasyon ve hesabın askıya alınması

1. Her gönderi, yorum, mesaj, grup, kanal, ders notu ve kullanıcı uygulama içinden şikâyet edilebilir; kullanıcılar engellenebilir.
2. Kurallara aykırı içerikleri kaldırabilir, hesapları geçici olarak askıya alabilir veya kalıcı olarak kapatabiliriz. İçeriğin kaldırıldığında gerekçesi sana bildirilir ve itiraz edebilirsin.
3. Kişilik haklarının ihlali ve kişisel veri ifşası bildirimleri öncelikli olarak (hedef 24 saat) incelenir.
4. Hukuka aykırı içerikler ve 5651 sayılı Kanun kapsamındaki kararlar yetkili mercilerle paylaşılabilir.

## 9. Hesabın kapatılması

Hesabını istediğin an uygulamadan (**Ayarlar → Gizlilik ve KVKK → Hesabımı sil**) veya web sitesindeki hesap silme sayfasından silebilirsin. Talepten sonra 30 gün boyunca giriş yapıp silmeden vazgeçebilirsin; süre sonunda hesabın ve içeriklerin kalıcı olarak silinir, grup sohbetlerindeki mesajların "Silinmiş kullanıcı" olarak anonimleştirilir. Yasal olarak saklanması zorunlu kayıtlar (5651 trafik kayıtları, onay kayıtları) profilinden ayrılarak yalnızca yasal süre boyunca saklanır.

## 10. Sorumluluğun sınırı

Hizmeti mevcut hâliyle sunarız ve kesintisiz veya hatasız çalışacağını garanti etmeyiz. Kullanıcıların birbirleriyle ilişkilerinden ve paylaşımlarından doğan zararlardan, kanunların izin verdiği ölçüde ve kasıt ile ağır ihmal hâlleri saklı kalmak üzere sorumlu değiliz. Tüketici olarak kanundan doğan hakların saklıdır.

## 11. Değişiklikler

Bu koşulları değiştirebiliriz. Yeni sürüm yayınlandığında uygulamaya bir sonraki girişinde gösterilir; kullanmaya devam etmek için yeni sürümü kabul etmen gerekir. Önceki sürümler saklanır.

## 12. Uygulanacak hukuk ve uyuşmazlıklar

Bu sözleşme Türkiye Cumhuriyeti hukukuna tabidir. Tüketici uyuşmazlıklarında Ticaret Bakanlığı'nca ilan edilen parasal sınırlar dahilinde tüketici hakem heyetleri, aşan durumlarda tüketici mahkemeleri yetkilidir.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('mesafeli_sozlesme', 1, 'Premium Abonelik Mesafeli Hizmet Sözleşmesi', $legal$# Premium Abonelik Mesafeli Hizmet Sözleşmesi

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

## Madde 1 — Taraflar

**Hizmet sağlayıcı:** [VERİ SORUMLUSU UNVANI], [ADRES], MERSİS/Vergi No: [MERSİS NO] / [VERGİ DAİRESİ VE NO], E-posta: [İLETİŞİM E-POSTASI], KEP: [KEP]

**Tüketici:** KampüsAğı'na kayıtlı, Premium aboneliği satın alan kullanıcı (kayıtlı e-posta adresi ve kullanıcı adıyla tanımlanır).

## Madde 2 — Konu

Bu sözleşme, tüketicinin KampüsAğı mobil uygulaması üzerinden elektronik ortamda satın aldığı Premium dijital hizmet aboneliğine ilişkin tarafların hak ve yükümlülüklerini 6502 sayılı Kanun ve Mesafeli Sözleşmeler Yönetmeliği'ne uygun olarak düzenler.

## Madde 3 — Hizmet, bedel ve ödeme

1. Hizmetin nitelikleri Premium Ön Bilgilendirme Formu'nda ve uygulamadaki Premium ekranında yer alır.
2. Bedel, satın alma anında Google Play ödeme penceresinde gösterilen, vergiler dahil tutardır.
3. Ödeme Google Play faturalandırma sistemi ile alınır; abonelik iptal edilmedikçe her dönem sonunda otomatik yenilenir.

## Madde 4 — İfa

Hizmet, Google Play'in ödemeyi onaylamasının ve satın almanın sunucumuzca doğrulanmasının ardından hemen tüketicinin hesabına tanımlanır.

## Madde 5 — Cayma hakkı

Elektronik ortamda anında ifa edilen hizmetlerde cayma hakkı bulunmaz (Yönetmelik md.15/1-ğ). Tüketici, satın almadan önce ifaya hemen başlanmasını açıkça onayladığını ve cayma hakkını kaybedeceğini bildiğini kabul eder.

## Madde 6 — İptal ve sona erme

Tüketici aboneliği Google Play üzerinden dilediği zaman iptal edebilir; iptal dönem sonunda geçerli olur. Hizmet sağlayıcı, Kullanım Koşulları'nın ağır ihlali hâlinde hesabı kapatabilir; bu durumda kanundan doğan haklar saklıdır.

## Madde 7 — Uyuşmazlık

Uyuşmazlıklarda Ticaret Bakanlığı'nca ilan edilen parasal sınırlar dahilinde tüketicinin yerleşim yerindeki veya işlemin yapıldığı yerdeki tüketici hakem heyetleri, aşan durumlarda tüketici mahkemeleri yetkilidir.

## Madde 8 — Yürürlük

Tüketici, satın alma ekranında bu sözleşmeyi ve Ön Bilgilendirme Formu'nu okuyup onayladığında sözleşme kurulmuş sayılır. Onay kaydı, metnin sürümü ve özetiyle (SHA-256) birlikte saklanır.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('premium_on_bilgilendirme', 1, 'Premium Abonelik Ön Bilgilendirme Formu', $legal$# Premium Abonelik Ön Bilgilendirme Formu

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

6502 sayılı Tüketicinin Korunması Hakkında Kanun ve Mesafeli Sözleşmeler Yönetmeliği uyarınca, Premium aboneliği satın almadan önce aşağıdaki bilgileri okumalısın.

## 1. Satıcı / hizmet sağlayıcı

- Unvan: [VERİ SORUMLUSU UNVANI]
- Adres: [ADRES]
- MERSİS / Vergi No: [MERSİS NO] / [VERGİ DAİRESİ VE NO]
- E-posta: [İLETİŞİM E-POSTASI] · KEP: [KEP]

## 2. Hizmetin temel nitelikleri

KampüsAğı Premium; Premium kanal açma (en fazla 5), kanal fotoğrafı, kanalda anket paylaşma ve daha fazla aktif ihtiyaç ilanı hakkı sağlayan, süreli bir dijital hizmet aboneliğidir. Premium'un sağladığı haklar uygulamadaki Premium ekranında güncel olarak listelenir.

## 3. Fiyat ve ödeme

- Fiyat, vergiler dahil olarak satın alma ekranında ve Google Play ödeme penceresinde gösterilir. Gösterilen fiyat esastır.
- Ödeme **yalnızca Google Play faturalandırma sistemi** ile alınır. Kart veya ödeme bilgilerin KampüsAğı ile paylaşılmaz.

## 4. Süre ve otomatik yenileme

- Abonelik aylık dönemler hâlinde sunulur ve **iptal edilmedikçe her dönem sonunda otomatik olarak yenilenir**; yenileme bedeli Google Play hesabına bağlı ödeme yönteminden tahsil edilir.
- Fiyat değişikliği olursa Google Play seni önceden bilgilendirir ve gerekli durumlarda onayını ister.

## 5. İptal

- Aboneliğini istediğin an **Google Play → Profil → Ödemeler ve abonelikler → Abonelikler** bölümünden veya uygulamadaki **Aboneliği yönet** bağlantısından iptal edebilirsin.
- İptal, içinde bulunulan dönemin sonunda geçerli olur; dönem sonuna kadar Premium devam eder.
- Hesabını silmen aboneliğini iptal etmez; aboneliği Google Play'den ayrıca iptal etmelisin.

## 6. Cayma hakkı

Mesafeli Sözleşmeler Yönetmeliği md.15/1-ğ uyarınca, **elektronik ortamda anında ifa edilen hizmetler ve tüketiciye anında teslim edilen gayrimaddi mallarda cayma hakkı kullanılamaz.** Premium haklar satın alma onaylandığı anda hesabına tanımlandığından, satın almadan önce **ifaya hemen başlanmasını açıkça onayladığını ve bu nedenle cayma hakkını kaybedeceğini kabul ettiğini** beyan etmen istenir. Bu onay verilmeden satın alma başlatılmaz. Google Play'in kendi iade politikası kapsamındaki hakların saklıdır.

## 7. Şikâyet ve başvuru

Şikâyetlerini [İLETİŞİM E-POSTASI] adresine iletebilirsin. Ticaret Bakanlığı'nca her yıl ilan edilen parasal sınırlar dahilinde tüketici hakem heyetlerine, aşan durumlarda tüketici mahkemelerine başvurabilirsin.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('saklama_imha_politikasi', 1, 'Kişisel Veri Saklama ve İmha Politikası', $legal$# Kişisel Veri Saklama ve İmha Politikası

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

Bu politika, Kişisel Verilerin Silinmesi, Yok Edilmesi veya Anonim Hale Getirilmesi Hakkında Yönetmelik uyarınca hazırlanmıştır.

## 1. Kayıt ortamları

Tüm kişisel veriler elektronik ortamda tutulur: Supabase PostgreSQL veritabanı, Supabase Storage (dosyalar), Supabase Auth (giriş bilgileri), Firebase Cloud Messaging (yalnızca bildirim belirteci üzerinden gönderim), Resend (gönderilen e-postaların kayıtları), Vercel (web sunucu kayıtları). Kâğıt ortamda kişisel veri tutulmaz.

## 2. Saklama süreleri

Süreler yönetim panelindeki uyum ayarlarından okunur; aşağıdaki değerler varsayılanlardır. Ayar değiştiğinde bu politikanın yeni sürümü yayımlanır.

| Veri | Saklama süresi | İmha yöntemi |
|---|---|---|
| Öğrenci belgesi (PDF) | Onay veya red kararından sonra en geç 30 gün | Dosyanın Storage'dan kalıcı silinmesi; kalan kayıtta yalnızca sonuç, tarih, doğrulayan ve SHA-256 özeti |
| Doğum tarihi | Saklanmaz (yalnızca kayıt anında yaş kontrolü) | — |
| Hesap ve profil verileri, içerikler, mesajlar | Üyelik süresince; silme talebinden sonra 30 günlük geri alma süresi sonunda | Kalıcı silme; grup ve kanal mesajları "Silinmiş kullanıcı" olarak anonimleştirme |
| Hareketsiz hesaplar | 2 yıl giriş yapılmazsa e-posta ile uyarı, 30 gün sonra | Kalıcı silme |
| 5651 trafik kayıtları (giriş, çıkış, başarısız giriş, şifre sıfırlama; IP, cihaz, zaman) | 2 yıl | Kalıcı silme (zincir başlangıç özeti imha kaydında tutulur) |
| Onay, aydınlatma ve rıza kayıtları | 10 yıl (ispat yükümlülüğü, genel zamanaşımı) | Kalıcı silme |
| Yönetici işlem kayıtları | 10 yıl | Kalıcı silme |
| İmha kayıtları | 10 yıl | Kalıcı silme |
| Uygulama hata raporları | 180 gün | Kalıcı silme |
| Veri dışa aktarma dosyası | 7 gün | Kalıcı silme |
| Veri sahibi başvuruları ve ihlal kayıtları | 10 yıl | Kalıcı silme |
| Satın alma kayıtları | Vergi Usul Kanunu ve Türk Ticaret Kanunu uyarınca 10 yıl; hesap silinince kişiden ayrılır | Anonimleştirme |
| Bildirim belirteci | Çıkış yapılınca veya FCM geçersiz bildirince | Kalıcı silme |

## 3. Periyodik imha

Otomatik imha işi **her gün** çalışır (yasal üst sınır olan 6 aylık periyodik imha süresinden çok daha sık). Her imha işlemi; hangi veri kategorisinin, hangi gerekçeyle (kullanıcı talebi, saklama süresi doldu, belge kararı, hareketsiz hesap), hangi yöntemle ve kaç kayıt olarak imha edildiği bilgisiyle, silinen içeriğin kendisi olmadan, değiştirilemez imha kayıtlarına yazılır. İmha raporu yönetim panelinde görüntülenir.

## 4. Yedekler

Veritabanı yedekleri barındırma sağlayıcısı (Supabase) tarafından alınır ve sağlayıcının yedek saklama süresi ([YEDEK SAKLAMA SÜRESİ]) sonunda kendiliğinden silinir. Yedekten geri dönüş yapılırsa, geri dönüş anından sonra imha edilmiş olması gereken veriler bir sonraki otomatik imha çalışmasında yeniden imha edilir.

## 5. Teknik ve idari tedbirler

Satır düzeyinde erişim kuralları, rol bazlı yönetici yetkileri, yöneticiler için iki adımlı doğrulama, değiştirilemez ve hash zinciriyle korunan işlem kayıtları, TLS ile şifreli iletim, sağlayıcı düzeyinde şifreli depolama, gizli anahtarların yalnızca sunucu ortam değişkenlerinde tutulması.

## 6. Sorumlular

Politikanın uygulanmasından [SORUMLU KİŞİ / BİRİM] sorumludur.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('telif_politikasi', 1, 'Telif Hakkı ve İçerik Kaldırma Politikası', $legal$# Telif Hakkı ve İçerik Kaldırma Politikası

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

KampüsAğı, 5846 sayılı Fikir ve Sanat Eserleri Kanunu (FSEK) ve 5651 sayılı Kanun kapsamında yer sağlayıcı olarak, kullanıcıların paylaştığı içeriği önceden denetlemez; hukuka aykırı içerikten haberdar edildiğinde kaldırır.

## Kullanıcının beyanı

Ders notu veya başka bir içerik yükleyen kullanıcı, yüklemeden önce şu beyanı onaylar:

> "Bu içeriğin hak sahibiyim veya paylaşma iznim var. Hocalara ait sınav sorularını ya da telifli kitap sayfalarını izinsiz paylaşmayacağım."

Beyan, tarih ve saatiyle içerikle birlikte kaydedilir. Gerçeğe aykırı beyandan doğan sorumluluk kullanıcıya aittir.

## Hak sahipleri için bildirim yolu

Eserinizin izinsiz paylaşıldığını düşünüyorsanız:

1. **Giriş gerektirmeyen web formu:** web sitemizdeki **Telif bildirimi** sayfası.
2. E-posta: [İLETİŞİM E-POSTASI] · KEP: [KEP] · Posta: [ADRES]

Bildirimde şunlar bulunmalıdır: adınız soyadınız (veya temsil ettiğiniz kurum), iletişim bilginiz, hak sahibi olduğunuz eser, ihlal edildiğini düşündüğünüz içeriğin uygulamadaki yeri (ders kodu, not başlığı, paylaşan kullanıcı adı veya bağlantı) ve bildirimin doğru olduğuna ve hak sahibi ya da yetkili temsilci olduğunuza dair beyanınız.

## Süreç

- Bildirim kayıt altına alınır ve yetkili moderatör tarafından incelenir.
- İhlal açıksa içerik erişime kapatılır; içeriği yükleyen kullanıcıya gerekçesi bildirilir ve itiraz hakkı tanınır.
- Tekrarlanan ihlallerde hesap kapatılabilir.
- Her karar gerekçesiyle değiştirilemez kayıtlarda saklanır.
- Mahkeme veya yetkili merci kararları ayrıca uygulanır.
$legal$);

insert into public.legal_documents (doc_type, version, title, content) values ('topluluk_kurallari', 1, 'KampüsAğı Topluluk Kuralları', $legal$# KampüsAğı Topluluk Kuralları

> **TASLAK — AVUKAT ONAYI GEREKLİ.**

KampüsAğı, öğrencilerin birbirine güvenle ulaşabildiği bir topluluktur. Bu kurallar Kullanım Koşulları'nın parçasıdır; ihlali içeriğin kaldırılmasına, hesabın askıya alınmasına veya kapatılmasına yol açar.

## Yasak olanlar

1. **Taciz ve zorbalık:** Bir kişiyi rahatsız etmek, aşağılamak, tehdit etmek, ısrarla istenmeyen mesaj göndermek, ifşa ile tehdit etmek.
2. **Nefret söylemi ve ayrımcılık:** Din, mezhep, dil, ırk, etnik köken, cinsiyet, cinsel yönelim, engellilik, siyasi görüş, memleket veya benzeri özellikler nedeniyle kişileri veya grupları aşağılamak, dışlamak, şiddete çağırmak. İlanlarda bu özelliklere göre ayrım yapmak (ör. "şu dinden ev arkadaşı aranıyor") da yasaktır.
3. **Kişisel veri ifşası:** Başkasının telefon numarasını, adresini, T.C. kimlik numarasını, öğrenci belgesini, fotoğrafını, konumunu veya özel yazışmalarını izni olmadan paylaşmak.
4. **Cinsel içerik:** Çıplaklık, pornografi, cinsel taciz. Reşit olmayanları içeren her türlü cinsel veya istismar içeriği derhal kaldırılır ve yetkili makamlara bildirilir.
5. **Telif ihlali:** Hak sahibinin izni olmadan kitap, ders kitabı sayfası, hocaya ait sınav soruları, ücretli ders içeriği, film, müzik vb. paylaşmak.
6. **Sahte hesap ve kimlik taklidi:** Başkası gibi davranmak, sahte bilgiyle hesap açmak, birden fazla hesap kullanmak.
7. **Spam ve dolandırıcılık:** Toplu/istenmeyen tanıtım, sahte ilan, kapora dolandırıcılığı, kimlik avı bağlantıları.
8. **Şiddet ve yasa dışı faaliyet:** Şiddeti, kendine zarar vermeyi, uyuşturucu, silah veya yasa dışı ürün/hizmet ticaretini özendirmek.

## Kendini koru

- Mesajlarında ve gönderilerinde T.C. kimlik numaranı, IBAN'ını veya telefon numaranı paylaşmadan önce iki kez düşün; uygulama bu durumda seni uyarır.
- Din, sağlık, siyasi görüş gibi özel nitelikli bilgilerini paylaşmak zorunda değilsin; bu bilgileri istemiyoruz.

## Şikâyet ve engelleme

Her gönderi, yorum, mesaj, grup, kanal, ders notu ve profil için **Şikâyet et**; her kullanıcı için **Engelle** seçeneği vardır. Şikâyet kategorileri: taciz, nefret/ayrımcılık, kişisel veri ifşası, kişilik hakkı ihlali, cinsel içerik, telif ihlali, sahte hesap, spam, diğer. Kişisel veri ifşası ve kişilik hakkı ihlali bildirimleri öncelikli incelenir. Şikâyet edenin kimliği şikâyet edilen kişiye gösterilmez.

## Kararlar ve itiraz

İçeriğin kaldırılırsa veya hesabın askıya alınırsa gerekçesi sana bildirilir. Karara uygulama içinden veya [İLETİŞİM E-POSTASI] adresine yazarak itiraz edebilirsin. Her moderasyon kararı gerekçesiyle kayıt altına alınır.
$legal$);
